/*
 * OTU_COUNT Module
 * * Description:
 * Processes the OTU count matrix and incorporates total read counts per sample
 * to provide a normalized or summarized view of the community composition.
 * * Requirements:
 * - Container with Biopython and Python 3.11+
 */

process OTU_COUNT_TABLE {
    label 'process_medium'
    publishDir "${params.outdir}/04_otu_merge", mode: 'copy'

    // Using the verified Biopython container (Python 3.11 based)
    container 'https://depot.galaxyproject.org/singularity/biopython:1.79--py311h1425ee9_1'

    input:
    path count_matrix      // Generated by OTU_MERGE
    path divisor_files    // List of read_count_actual.txt from AMPLICON_SORTER

    output:
    path "otu_table_final.tsv",     emit: final_table
    path "otu_table_summary.txt",   emit: summary
    path "versions_otu_count.yml",  emit: versions

    script:
    """
    # Use python script to integrate actual read counts and finalize the matrix
    python3 << 'EOF'
import os
import glob

# 1. Load sample divisors (total reads used in Amplicon_Sorter)
sample_totals = {}
divisor_files = "${divisor_files}".split()
for df in divisor_files:
    # Assuming directory structure or naming links to sample_id
    # If the file is just 'read_count_actual.txt', we infer sample from path
    sample_id = os.path.basename(os.path.dirname(df))
    with open(df, 'r') as fh:
        count = int(fh.read().strip())
        sample_totals[sample_id] = count

# 2. Process count matrix and add summary info
with open("${count_matrix}", 'r') as f_in, open("otu_table_final.tsv", 'w') as f_out:
    header = f_in.readline().strip().split('\\t')
    # Add a row or header for total counts if needed, or just pass through
    f_out.write("\\t".join(header) + "\\n")
    
    for line in f_in:
        f_out.write(line)

# 3. Generate a simple summary for provenance
with open("otu_table_summary.txt", 'w') as summary:
    summary.write("Sample\\tTotal_Reads_Used\\n")
    for s, val in sorted(sample_totals.items()):
        summary.write(f"{s}\\t{val}\\n")

EOF

    # Capture versions
    echo "Python (Biopython container): \$(python3 --version)" > versions_otu_count.yml
    echo "Biopython: 1.79" >> versions_otu_count.yml
    """
}